### ISSUE TITLE
useDelta on first render

### ISSUE THREAD

**Issue by lishine** [malerba118/react-delta#6]
It returns not null on first render
I think it should return null

**Comment by lishine** [comment]
Currently I am forced to use it like this:
```
    useConditionalEffect(() => {
        if (publishing) {
        } else {
        }
    }, deltaPublishing && deltaPublishing?.hasOwnProperty('prev'))
```
instead of just ```}, deltaPublishing)```

**Comment by malerba118** [comment]
Yes, this is intentional and consistent with the way that useEffect runs effects in that, effects will always run on the first render regardless of the value passed. The way you have done it is how i would do it as well. The rationale is that any value passed on the first render is different than the previous value which did not exist. Even if undefined is passed to useDelta on the first render, this is still considered to have changed because an undefined value is different than a non-existent key. The use-case to run effects on the first render is very common whereas the use-case not to run effects on the first render is less common and i can't support both because they're mutually exclusive.
